### ISSUE TITLE
Copy all blocks -> paste doesn't work if header was copied

### ISSUE THREAD

**Issue by stefankip** [PerplexDigital/Perplex.ContentBlocks#20]
I have this header block with 3 content blocks.
When I copy all blocks and try to paste them, I get this message:
> Cannot paste a header on a page with another header. If the header should be replaced, remove it first.

I'd rather be able to choose to only paste the Content blocks without the Header block.

**Comment by PerplexDaniel** [comment]
Fair enough, I agree the current behavior is not ideal. The easiest (i.e., no additional UI needed) change for this would be to simply paste all blocks & skip the header, showing a notification saying the header wasn't copied because there was already an existing header. Rather than blocking the entire paste action as it does at the moment. The user can then still go back to copy the header if desired. Of course the best option is to offer a choice but that takes a bit more time whereas the other option solves the issue at hand as well I'd say. Will look into that soon.

**Comment by PerplexDaniel** [comment]
@stefankip FYI just released a release candidate for `1.5.0` (available on NuGet, make sure to include Prerelease versions) which includes the proposed fix for this issue. Will probably release 1.5.0 later this week or next week, should be the same as the release candidate unless some bugs are found.

**Comment by stefankip** [comment]
Just wanted to let you know this seems to work fine, nice job! 🤜🏼🤛🏼

**Comment by PerplexDaniel** [comment]
Fixed in v1.5.0
