### ISSUE TITLE
Add ability to translate text

### ISSUE THREAD

**Issue by stefankip** [PerplexDigital/Perplex.ContentBlocks#22]
It would be nice to have the ability to [use language files](https://our.umbraco.com/documentation/extending/language-files/) to change and translate the text used in the editor.

**Comment by AndersBrohus** [comment]
I would like to help create the danish translations if needed :)

**Comment by PerplexDaniel** [comment]
Sure, sounds like a good addition. Not sure if we have time for this anytime soon so any PRs are appreciated :)

We should make sure the localization keys are unique and do not interfere with any built-in ones from Umbraco, so I suppose a top-level `<area>` with alias `"perplexContentBlocks"` will be enough. Because Umbraco is also working on some block editor adding `"perplex"` is probably necessary otherwise that wouldn't be needed.

**Comment by AndersBrohus** [comment]
I got a WIP right now :)

Will make a PR in a second then you guys can review it and see if it's missing somethinig @PerplexDaniel and @stefankip :)

**Comment by PerplexDaniel** [comment]
Hey guys, just merged both of your contributions. Thanks! Will be released probably next week.
