### ISSUE TITLE
Add option to skip header block

### ISSUE THREAD

**Issue by stefankip** [PerplexDigital/Perplex.ContentBlocks#24]
Maybe I'm missing something, but I couldn't find an option to skip the header block for some pages.
I've set-up the datatype to use a Header + Blocks lay-out, but on some pages I don't want to have a Header block.
For now I created a 'No header' header block, but ideally I think it would be nice to be able to use no header OOTB.

**Comment by PerplexDaniel** [comment]
You mean make the header block optional right? That is, be able to leave it empty and still input blocks. Currently the "Add content" button for other blocks only shows when the header is set, which makes the header more or less mandatory indeed. 

I suppose "Make header optional" or something similar could be added as an option to the datatype configuration, which immediately "unlocks" the ability to add blocks underneath the header. I'll probably have a look at sometime in the next two weeks.

**Comment by PerplexDaniel** [comment]
I looked into this a little. The header technically isn't mandatory at the moment, it is not validated as such on the server or anything. You can save a page just fine with an empty header. It's just that the UI prevents you at the moment to leave the header empty _but add other blocks_.

So the configuration option I was talking about ("Make header optional") would really only control the user interface. Which is fine, I just want to explain that the option I will add will be named differently because the header is already optional in all cases. If anything, we could add an option later to actually make the header mandatory :-)

So the option I will add in the near future will probably be something like "allow adding blocks when header is empty" (default false), which will then just do some UI change and show both Add header / Add content simultaneously, allowing the user to just skip the header and leave it empty. Otherwise no code changes would be needed for this.

![header](https://user-images.githubusercontent.com/24297947/87531240-b6580200-c691-11ea-9375-7555ed514224.png)

**Comment by stefankip** [comment]
Sounds like a great solution 👌🏼

**Comment by PerplexDaniel** [comment]
@stefankip FYI just released a release candidate for `1.5.0` (available on NuGet, make sure to include Prerelease versions) which includes the proposed fix for this issue. Will probably release 1.5.0 later this week or next week, should be the same as the release candidate unless some bugs are found.

**Comment by stefankip** [comment]
Nice, will install the RC right away and report back if I run into anything.

**Comment by stefankip** [comment]
Just wanted to let you know this seems to work fine, nice job! 🤜🏼🤛🏼

**Comment by PerplexDaniel** [comment]
Fixed in v1.5.0
