### ISSUE TITLE
Add delegate for LimitToDocumentTypes

### ISSUE THREAD

**Issue by stefankip** [PerplexDigital/Perplex.ContentBlocks#30]
I'm in this multi-tenant situation and I prefix all document types based on the type of website.
I'd love to be able to filter the document types via the LimitToDocumentTypes property, but with a custom delegate implementation.
So I would be able to use something like;
```csharp
LimitToDocumentTypes = (content) => { // content is IContent
    return content.ContentType.Alias.StartsWith("shop");
}
```

**Comment by PerplexDaniel** [comment]
Looks pretty nice, but not sure if this can/will be changed soon (breaking change). We are also passing the `IContentBlockDefinition` to the backoffice angular code as JSON so that will not work very well with a delegate property.

However, you can simply work around this by retrieving ContentTypes and filtering them where you are registering your blocks, right? There you can still use your delegate to filter the content types. That is, something like this:

```csharp
var shopAliases = _contentTypeService
    .GetAll()
    .Where(ct => ct.Alias.StartsWith("shop"))
    .Select(ct => ct.Alias);

// And still assign as IEnumerable<string>
LimitToDocumentTypes = shopAliases;
```

**Comment by stefankip** [comment]
Yeah sure, nice work-around for now and I understand it can be hard if it's passed over to the angular front-end.
I would not suggest using the same `LimitToDocumentTypes` property name, so then it wouldn't be a breaking change though.

I guess the work-around you mentioned is fine!
