### ISSUE TITLE
Issue on 8.7

### ISSUE THREAD

**Issue by seanrockster** [PerplexDigital/Perplex.ContentBlocks#40]
Hi

Just trying out umbraco 8.7 and also trying out Perplex.ContentBlocks. From the QuickStart code..

`
@using Perplex.ContentBlocks.Rendering;
@Html.RenderContentBlocks(Model.Blocks)`

My alias is Blocks rather than ContentBlocks but I'm not sure that matters.

With the code to render the example block, I get this error

`Compiler Error Message: CS1503: Argument 2: cannot convert from 'Umbraco.Core.Models.Blocks.BlockListModel' to 'Perplex.ContentBlocks.Rendering.IContentBlocks'`

**Comment by PerplexDaniel** [comment]
The alias does not matter. However, judging from the error message your `"blocks"` property is not using a `Perplex.ContentBlocks` datatype but the new Umbraco Block List editor. 

Can you verify at your document type settings the `"blocks"` property is actually using the datatype `Perplex.ContentBlocks`?

**Comment by seanrockster** [comment]
Yes, its using Perplex.ContentBlocks and the property works ok.

![image](https://user-images.githubusercontent.com/2518884/93060606-48689080-f66a-11ea-9018-3d4d6f280963.png)

![image](https://user-images.githubusercontent.com/2518884/93060838-9bdade80-f66a-11ea-82cb-b3cc84b11e31.png)

**Comment by PerplexDaniel** [comment]
Interesting. Did you run ModelsBuilder again? Or are you using PureLive mode? Because clearly Umbraco thinks the `"blocks"` property is an `Umbraco.Core.Models.Blocks.BlockListModel`. I have already tested ContentBlocks on 8.7 and that worked fine so I think there is some small mistake in your configuration somewhere. 

You can also try to retrieve the value as `Model.Value<Perplex.ContentBlocks.Rendering.IContentBlocks>("blocks")` and use that instead of `Model.Blocks` in the `RenderContentBlocks` method.

**Comment by seanrockster** [comment]
Yeah, looks like something was clogged up. I deleted all the models, removed all the properties i created, republished everything and the error went away. I must have created a similar property with the built-in block editor as i'm trying them both for an upcoming project. Problem solved.
