### ISSUE TITLE
Block List support

### ISSUE THREAD

**Issue by joepvtl** [PerplexDigital/Perplex.ContentBlocks#41]
Hey Daniël,

Are you planning on supporting the new Block List datatype inside of the Content Blocks?
It seems like this would be a good feature :)

(I know this was built on top of NC, but was just wondering if this had crossed your mind)

Interested to hear your thoughts.

-Joep

**Comment by PerplexDaniel** [comment]
We haven't really made any plans around the Block List Editor here.
How do you envision supporting the Block List Editor _inside_ the Content Blocks? The Block List Editor is simply another way to edit a list of blocks made of published elements, so at first glance it doesn't really make sense to me to make a block with a Block List Editor inside of it, if that's what you mean. Although that should just work out of the box more or less, I have not tried that yet.

**Comment by PerplexDaniel** [comment]
Oh I wasn't aware of the Block Editor already using some new data storage model. I saw an RFC to store it in a different way than JSON but didn't check what they use at the moment for the Block Editor.

So I am assuming you changed the `DataTypeId` or `DataTypeKey` of an `IContentBlockDefinition` and point that to a Block Editor datatype? That will indeed not work, at all. We use some of the NestedContent code (e.g. the `NestedContentSingleValueConverter`) in our backend code, so if it suddenly has to handle a Block List in that situation it will probably crash. So that can definitely *not* be swapped out at the moment. The underlying tech has to be NestedContent.

**Comment by joepvtl** [comment]
What I meant is that it uses an other JSON model and I think NC will probably go obsolete, since the Block Editor has the same functionalities NC has but even more. That's why I prefer using the Block Editor instead for new projects since it is more future proof then NC.

**Comment by joepvtl** [comment]
I think you were talking about storing Elements in a seperate place RFC.

**Comment by PerplexDaniel** [comment]
> What I meant is that it uses an other JSON model and I think NC will probably go obsolete, since the Block Editor has the same functionalities NC has but even more.

Yeah I suppose that's true. But in the near future I don't think we will transition ContentBlocks to that in the near future, considering it's 8.7+ only so that will break compatibility with all older installations. 

However, we will certainly look into the Block Editor soon so if it provides a lot of advantages to replace NestedContent as our underlying tech it is not out of the question for a 2.0 release or something :)

**Comment by PerplexDaniel** [comment]
If anything happens around this topic I'll re-open.
