### ISSUE TITLE
Is the latest version compatible with v13?

### ISSUE THREAD

**Issue by PanktiBodiwala** [PerplexDigital/Perplex.ContentBlocks#84]
Hi Team,

I'm upgrading my project from v11.4.2 to v13. I upgraded perplex to the latest version (3.0) however after an upgrade, every block is showing an error 'Block definition not found'. Neither does it allow me to add a new content item, instead showing an error 'No Content Block definition found'.

I wonder if it is because of the Nested Content being deprecated in v13?

Please let me know if you need any further info.

Thanks

**Comment by PanktiBodiwala** [comment]
Hi Daniel,

Thank you for the guidance. It is working now.

Out of curiosity, are you planning to introduce a migrator that can convert the NC blocks to the BLE? Would be extremely helpful in the future when deprecated property editors would not be available at all.

Kind Regards

**Comment by PerplexDaniel** [comment]
Good to hear it works.

> are you planning to introduce a migrator that can convert the NC blocks to the BLE?

While I cannot make any promises it is likely that for the next Umbraco LTS we at Perplex also need to migrate to either the native Block List or migratie ContentBlocks itself to use BlockList as base rather than NestedContent. Either way we probably need some sort of data migration from NC -> BL, so I do expect some sort of `Perplex.ContentBlocks.DataMigration`  package that will migrate data in some way (either to standalone BlockList types or to ContentBlocks with BlockList as underlying data model).

Not sure though, and regardless this will probably only be released around the time v17 (next LTS) is out and not when v14 (first major without NestedContent) is released since it's not LTS. v13 will be supported longer than all of v14 - v16.

Hope this gives you enough info, closing this now since your issue has been resolved!

**Comment by PanktiBodiwala** [comment]
Thanks Daniel, this makes sense.
